import { Inter } from "next/font/google";
import "./globals.css";
import Demo from "./components/Demo";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-row'>
          <div className='min-h-screen w-[300px]'>
            <Demo/>
          </div>
          <div className='w-full min-h-screen flex'>
          {children}
          </div>
        </div>
        
        </body>
    </html>
  );
}
